### ISSUE TITLE
integrate with Biz Ops

### ISSUE THREAD

**Issue by apaleslimghost** [Financial-Times/nori#117]
Biz Ops is the source of truth for repo ownership at the FT. being able to query it to load e.g. "every repo owned by the Platforms team" would make most of our use cases easier. i don't know what the best way of querying it would be; writing GraphQL as an input would work but it'd be difficult to construct a query in the terminal (e.g. with the GraphQL playground's autocomplete).

also, since Biz Ops/SSV are being used to track migrations, nori should be able to make Biz Ops changes as part of a migration (as an alternative to tracking in Github Projects).

**Comment by jkerr321** [comment]
@andygout @apaleslimghost What's the use case for this that isn't solved by looking at a Team's page in Biz Ops which lists all the systems they deliver? I.e. What's an example of when it will be useful to have this data in a form we can work with programatically?

I'm thinking about Q4 projects for Ops Cops and this might be a good candidate, but want to understand what problem it's solving first. Thanks!

**Comment by andygout** [comment]
@jkerr321 I think (though may be wrong) it's all part of removing the manual element from of such tasks.

Once you have the list of repos on which you want to run a script, that repeated process is automated, which is great.

But it would be even better to automate that initial compiling of repos, which is still a manual task.
