### ISSUE TITLE
do not assume main branch is called "master"

### ISSUE THREAD

**Issue by apaleslimghost** [Financial-Times/nori#122]
this happens in a number of places, notably in the `clone` operation and `pr` undo step. don't know how to work out what the main branch is called, maybe get the info from github? or keep track of it when the repo is cloned?

**Comment by antonsamper** [comment]
this is still relevant

**Comment by apaleslimghost** [comment]
bad stalebot

**Comment by apaleslimghost** [comment]
this will be covered by [CPP-446](https://financialtimes.atlassian.net/browse/CPP-446)
