### ISSUE TITLE
Rate limit PR creation

### ISSUE THREAD

**Issue by ivomurrell** [Financial-Times/nori#149]
After creating 21 PRs in a row the 22nd PR returned an HTTP error for me:

> You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.

(The rest of the PRs were created without issue.)

We should add some rate limiting to calls to the GitHub API so we avoid sporadically getting this error.

**Comment by serena97** [comment]
Have opened https://github.com/Financial-Times/nori/pull/164 for this - it differs to 819922a as the PR's change will allow for retries to handle the creation of the subsequent PRS
