### ISSUE TITLE
Don't push a branch if there are no commits

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/nori#26]
If when the transformation runner executes the against a repository it doesn't make any commits - if there are no changes to make, or if an error occurs - the transformation runner _should not_ push the branch to the remote for that repository. It should log a message to tell the user that pushing the branch has been skipped.

#### Technical notes

This will probably require a `diff` method to be added to the [git tooling helper](https://github.com/Financial-Times/tooling-helpers#git).

**Comment by quarterto** [comment]
oh no stalebot no
