### ISSUE TITLE
rich preview

### ISSUE THREAD

**Issue by apaleslimghost** [Financial-Times/nori#49]
the current `preview` merely outputs the data JSON. that's not very readable or helpful. instead, like with the short-preview header, each data type should have a `preview` method that outputs nicely rendered preview. for example for the `branch` type this should be a `git diff` against the base branch

**Comment by quarterto** [comment]
this should open another `enquirer` menu along the lines of:

```
> clones
- localBranches
- remoteBranches
- prs
- cards
```

### select `clones`:
```
> financial-times-sandbox/abandoned-toothbrush
- financial-times-sandbox/western-storm
```

selecting one of these opens the folder

### select `localBranches`:
```
> financial-times-sandbox/abandoned-toothbrush#branch
- financial-times-sandbox/western-storm#branch
```

selecting one of these runs `git diff`

### select `remoteBranches`:
```
> financial-times-sandbox/abandoned-toothbrush#branch
- financial-times-sandbox/western-storm#branch
```

selecting one of these opens the github compare page

### select `prs`:
```
> financial-times-sandbox/abandoned-toothbrush#137
- financial-times-sandbox/western-storm#137
```

selecting one of these opens the PR in the browser

und so weiter
