### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/nori#68]
We should improve upon error situations and provide more helpful error messages.

```
✔ path to a text file of repositories · test
{ [Error: EISDIR: illegal operation on a directory, read] errno: -21, code: 'EISDIR', syscall: 'read' }
```

**Comment by quarterto** [comment]
@sjparkinson if this is the only case, i've fixed this in my help text & papercuts branch. if not, can you provide more examples please?

**Comment by quarterto** [comment]
i'm going to treat this as an umbrella issue for all error handling 🙂

**Comment by sjparkinson** [comment]
I imagine there would be a similar one for the script path too.
