### ISSUE TITLE
Add label or description to indicate it is nori creating the PR

### ISSUE THREAD

**Issue by taktran** [Financial-Times/nori#80]
For future benefits, it would be nice to be able to filter PRs that were created by nori. Not that we ever make mistakes 😬 , but knowing which PRs were created by nori could be useful for undoing things, or even just searching manually through PRs.

Some ways to do this:

* Add a tagline at the end of the PR description eg, `🍙 This PR was created with [nori](https://github.com/Financial-Times/nori).`
* Add a `nori` label to the PR

**Comment by quarterto** [comment]
label is more complicated because it would need an extra couple of github api calls to ensure the label exists first. i'm up for a footer though
