### ISSUE TITLE
Move project creation to before PRs are created

### ISSUE THREAD

**Issue by taktran** [Financial-Times/nori#85]
It'd be very nice to see the projects being created as the PRs are created. Right now project board are created _after_ the PRs, so you can't do this.

It'd be nice to create the project at the beginning, provide the link, then run the PR creation part.

**Comment by quarterto** [comment]
this is doable by splitting the current `project` operation into two, along the lines of `create-project`, with no inputs, outputting `project`, and `create-project-cards`, with inputs `['prs', 'project']` and output `project-cards` (i guess?)
