### ISSUE TITLE
Document the capability to use repo name inside the script for conditional output (or an alternative)

### ISSUE THREAD

**Issue by umbobabo** [Financial-Times/nori#87]
# Scenario
You want to apply changes to a lot of repos but with different input.
Example, I want to re-assign all the repos to different codeowners:

repo-A >> Mike_The_Cat
repo-B >> Mike_The_Cat
repo-C >> Judith_The_Dog
repo-D >> Loren_The_Frog

# Current workaround
It seems possible (but not documented yet) to use this Env var in the script
https://github.com/Financial-Times/nori/blob/97ff5c6305685066f6ca39c2682ca64377434433/src/commands/run-script.js#L74

Anyway, this implies that I have to map the repos in the script so I can then create the desired output.
I don't think it's an ideal solution.

# Suggested solution

IMO, a better approach could be that you can pass parameters in the repos list (let say in CSV format) like...
```
repo-A, Mike_The_Cat
repo-B, Mike_The_Cat
repo-C, Judith_The_Dog
repo-D, Loren_The_Frog
```
the script will then receive this as parameters that can be used in a simple way.

**Comment by quarterto** [comment]
should still do this
