### ISSUE TITLE
Pasting a carriage return in the body of a PR ignores body

### ISSUE THREAD

**Issue by taktran** [Financial-Times/nori#89]
When you paste body content in the PR step with a carriage return, `nori` creates the PR with an empty body and ignores what was pasted.

To replicate:

1. Get to the PR step in `nori`
2. Create a title
3. Paste the following into body:

```
Some message

Another thing
```

4. PR will be created, but body will be missing

**Comment by taktran** [comment]
Current hack is to use `<br/><br/>` to create spaces in markdown eg, https://github.com/Financial-Times/app-push-notifications/pull/31

**Comment by taktran** [comment]
Seems like an issue with how enquirer handles input. It thinks the newlines are submit events.

There is an issue that seems to say [multiline input is supported](https://github.com/enquirer/enquirer/issues/27#issuecomment-437691963), but I haven't been able to get it to work. I've added a comment to the issue https://github.com/enquirer/enquirer/issues/27#issuecomment-497774599

**Comment by quarterto** [comment]
since this is an enquirer bug, we should use their issue to track it, and hopefully fix it ourselves there
